release prep
lexibank/tryonsolomon pull request #8
Opened 2024-07-18 08:01 UTC by FredericBlum

Please review this PR carefully. The dataset was not previously included, but lingered around in the lexibank-repo. If I didn't miss anything in my own review, it is a good fit, but we better make sure it doesn't have serious problems.

2024-07-18 08:23 UTC, SimonGreenhill reviewed
Only issue is the author name, Darrell T. Tryon, otherwise all looks good.

2024-07-18 08:23 UTC, SimonGreenhill commented on .zenodo.json
> +            "name": "T. Tryon"
Should be Darrell T. Tryon

2024-07-18 12:45 UTC, LinguList approved these changes

2024-07-31 10:21 UTC, chrzyki requested changes

2024-07-31 10:21 UTC, chrzyki commented on metadata.json
> +    "citation": "Tryon, Durrell T. and Hackman, Brian D. (1983): Solomon Islands Languages: An internal classification. Canberra: Pacific Linguistics.",
There name is misspelled here so the dataset needs a rebuild after the metadata change.

2024-07-31 11:29 UTC, FredericBlum commented
I have added those changes now @chrzyki

2024-07-31 11:54 UTC, chrzyki commented
> I have added those changes now @chrzyki

In https://github.com/lexibank/tryonsolomon/pull/8/commits/721bbd080cc845d5685a50504e68d4775d47050d? AFAICT it's still 'Durrell' instead of 'Darrell' in the metadata.

2024-07-31 11:59 UTC, chrzyki approved these changes

2024-08-01 10:57 UTC, merged